DROP TABLE IF EXISTS substations_equipment;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS substations;

CREATE TABLE substations (
    voltageclass integer,
    id integer generated by default as identity primary key,
    name varchar(255)
);

create table equipment (
    id integer  generated by default as identity primary key,
    substation_id integer,
    name varchar(255),
    type varchar(255),
    foreign key (substation_id) references substations(id)
);


insert into substations(voltageclass, name)
    values (110, 'Murzikovo'),
           (220, 'Beliy Klik'),
           (500, 'Puka4effskaya'),
           (110, 'Wufffelnaya');

insert into equipment(type, name, substation_id)
values ('Transformer', 'T1', 1),
       ('Line', 'W1', 1),
       ('Connector', 'Q1', 1),
       ('Connector', 'Q2', 1),
       ('Connector', 'Q3', 1),
       ('RelayProtect', 'EKRA 210.05-01', 1),

       ('Transformer', 'AT1', 2),
       ('Line', 'W1', 2),
       ('Line', 'W2', 2),
       ('Connector', 'Q1', 2),
       ('Connector', 'Q2', 2),
       ('RelayProtect', 'EKRA 210.04-02', 2),

       ('Transformer', 'AOTDCTN-500', 3),
       ('Line', 'W1', 3),
       ('Connector', 'Q1', 3),
       ('Connector', 'Q2', 3),
       ('RelayProtect', 'EPZ-1636', 3),

       ('Connector', 'Q1', 4),
       ('Connector', 'Q0', 4);


